### PR TITLE
Use get_option() instead of get_site_option()

### PR DESCRIPTION
**Pull request by florianbrinkmann**
The plugin uses `get_site_option()` to get option values, but `update_option()` to set it. That does not work on multisites, this PR fixes that by replacing `update_option()` with `update_site_option()`.

### CODE REVIEW

**Comment by jackjamieson2** [comment]
Thanks for this! I’ll review and merge this as soon as I can (alongside a few other long needed dependency updates etc)

**Comment by florianbrinkmann** [comment]
You’re welcome! I just started thinking if it maybe would be better to use `get_option()` and `update_option()`, so that on a multisite one could have different channels and sites per site.

**Comment by florianbrinkmann** [comment]
I just updated the PR, I guess it makes more sense this way.

**Comment by jackjamieson2** [comment]
Hi @florianbrinkmann   Sorry I totally lost track of this! 

@dshanske, since you're making a few changes, do you know of any potential conflicts this could introduce?

**Comment by florianbrinkmann** [comment]
No problem @jackjamieson2!

**Comment by dshanske** [comment]
There's no potential conflict yet. I haven't dug down into anything. So merging isn't an issue

**Pull request merged**
